export const newNations = [
  {
    team: "Brazil",
    sport: "Soccer",
    country: "Brazil",
    capitalCity: "Brasilia",
    animal: "Jaguar",
    stadium: "Maracana",
    food: "Feijoada",
  },
  {
    team: "Germany",
    sport: "Soccer",
    country: "Germany",
    capitalCity: "Berlin",
    animal: "Eagle",
    stadium: "Allianz Arena",
    food: "Bratwurst",
  },
  {
    team: "Japan",
    sport: "Baseball",
    country: "Japan",
    capitalCity: "Tokyo",
    animal: "Crane",
    stadium: "Tokyo Dome",
    food: "Sushi",
  },
  {
    team: "USA",
    sport: "Basketball",
    country: "USA",
    capitalCity: "Washington DC",
    animal: "Bald Eagle",
    stadium: "Madison Square Garden",
    food: "Hamburger",
  },
]; 