export const toolData = [
  {
    name: "Rojo",
    type: "Build Tool",
    language: "Rust",
    purpose: "Roblox Project Sync",
    platform: "Cross-platform",
    category: "Development",
    status: "Active",
  },
  {
    name: "Roblox-TS",
    type: "Compiler",
    language: "TypeScript",
    purpose: "TypeScript to Lua",
    platform: "Node.js",
    category: "Development",
    status: "Active",
  },
  {
    name: "Studio",
    type: "IDE",
    language: "C++",
    purpose: "Roblox Development",
    platform: "Windows/Mac",
    category: "Development",
    status: "Active",
  },
  {
    name: "Luau",
    type: "Language",
    language: "Lua",
    purpose: "Roblox Scripting",
    platform: "Roblox",
    category: "Runtime",
    status: "Active",
  },
  {
    name: "Git",
    type: "Version Control",
    language: "C",
    purpose: "Source Management",
    platform: "Cross-platform",
    category: "Development",
    status: "Active",
  },
  {
    name: "VS Code",
    type: "Editor",
    language: "TypeScript",
    purpose: "Code Editing",
    platform: "Cross-platform",
    category: "Development",
    status: "Active",
  },
  {
    name: "npm",
    type: "Package Manager",
    language: "JavaScript",
    purpose: "Dependency Management",
    platform: "Node.js",
    category: "Development",
    status: "Active",
  },
  {
    name: "Webpack",
    type: "Bundler",
    language: "JavaScript",
    purpose: "Module Bundling",
    platform: "Node.js",
    category: "Build",
    status: "Active",
  },
]; 